### ISSUE TITLE
RFE: optionally specify keys to attempt to parse

### ISSUE THREAD

**Issue by mfowlewebs** [gmr/fluent-plugin-json-in-json#1]
Hello,

Rather than attempting to deserialize/parse each key and every key, it'd be pleasant to be able to specify a list of keys to try and deserialize/parse.

**Comment by ghost** [comment]
+1

**Comment by scalp42** [comment]
@mfowlewebs @0913925162 @gmr if you can review: https://github.com/gmr/fluent-plugin-json-in-json/pull/2
