### ISSUE TITLE
Can I please take over?

### ISSUE THREAD

**Issue by arcivanov** [gmr/fluent-plugin-json-in-json#6]
I would like to take over supporting this plugin if you don't mind. Could you please transfer repo to @arcivanov?

Thanks!

**Comment by dawidmalina** [comment]
@gmr it would be nice if we could bring this project back to live and looks like we have @arcivanov whose update this project on his fork.

**Comment by alikhil** [comment]
I took the repo of @arcivanov and published the plugin as `fluent-plugin-json-in-json-2`. It works pretty fine. Here is my [fork](https://github.com/alikhil/fluent-plugin-json-in-json)

**Comment by gmr** [comment]
Sorry it took so long to respond. I've invited @arcivanov as a collaborator.
